trigger:
  batch: true
  branches:
    include:
    - '*'

variables:
  - group: gswa-pypi
  - group: gswa-jfrog
  # for releases
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  # for integration testing
  - name: isRC
    value: $[contains(variables['Build.SourceBranch'], 'releases/')]
  # for modifying/reviewing pipeline
  - name: isCICD 
    value: $[contains(variables['Build.SourceBranch'], 'cicd')]

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: 'Unit Tests'
  condition: always()
  jobs:
    - job: TestCoverage
      displayName: 'Test coverage'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: '.[tests] pytest-azurepipelines'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m pytest --cov-report xml:tests/cov.xml --cov tests/
          displayName: 'Test .[tests]'
        
        - task: PublishCodeCoverageResults@2
          inputs:
            summaryFileLocation: '**/tests/cov.xml'
            pathToSources: '$(System.DefaultWorkingDirectory)/src/'
            failIfCoverageEmpty: true

- stage: Xray
  displayName: 'Xray Scan'
  trigger: manual
  isSkippable: false
  jobs:
    - job: BuildDependencies
      displayName: 'Install, build, and scan'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m build .
          displayName: 'Python build'
        
        - script: |
              curl -fL https://install-cli.jfrog.io | sh
              jf config add jfrog-bot \
              --url="$(JFROG_URL)" \
              --access-token="$JFROG_ACCESS_TOKEN" \
              --interactive=false
          env:
            JFROG_URL: $(jfrog_url)
            JFROG_ACCESS_TOKEN: $(jfrog-bot-token)
          displayName: Install and configure JFrog CLI

        - script: |
            jf scan dist/ --format='json' > xray.json
            jf scan dist/ --format='sarif' > xray.sarif
          displayName: 'Xray Scan'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: xray.sarif
            artifactName: CodeAnalysisLogs
          env:
            BUILD_NAME: $(Build.DefinitionName)
            BUILD_NUMBER: $(Build.BuildNumber)
          displayName: 'Publish SARIF artifact'

        - script: |
            python - <<'EOF'
            import json
            import sys
            sarif_file = "xray.json"
            with open(sarif_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            scanned_components = [
                item["component_id"]
                for item in data
                if "components"
                if "component_id" in item.keys()
            ]
            
         
            if "vulnerabilities" not in data[-1].keys():
              print("No vulnerabilities detected")
              sys.exit(0)
            elif  "vulnerabilities" in data[-1].keys(): 
              num_vulnerabilities = len(data[-1]["vulnerabilities"])
              if num_vulnerabilities > 0:
                  print(f"{num_vulnerabilities} High or Critical vulnerabilities detected")
                  sys.exit(1)


          displayName: 'Parse Vulnerabilities in xray Report'

- stage: Build
  displayName: 'JFrog Build and Publish'
  condition: and( succeeded('Test'), succeeded('Xray'), or(eq(variables.isMain, true), eq(variables.isRC, true), eq(variables.isCICD, true)) )
  dependsOn: 
    - Test
    - Xray
  jobs:
    - job: BuildDependencies
      displayName: 'Install and build'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'
        
        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m build .
          displayName: 'Python build'

        - script: |
            ls -lah dist/ 
            twine upload --repository-url $(artifactory_pypi_url) dist/*
          env:
            TWINE_USERNAME: $(jfrog_bot_username)
            TWINE_PASSWORD: $(jfrog-bot-token)
          displayName: Upload to JFrog Artifactory

# - stage: Release
#   displayName: 'Bells and Whistles'
#   dependsOn: 
#     - Test
#     - Xray
#     - Build
#   condition: and( succeeded('Test'), succeeded('Xray'), succeeded('Build'), eq(variables.isMain, true))
#   jobs:
#     - job: BuildDependencies
#       displayName: 'Install and build'
#       steps:                
#         - task: UsePythonVersion@0
#           inputs:
#             versionSpec: '3.12'
#             addToPath: true
#             architecture: 'x64'

#         - script: |
#             python -m pip install twine
#             python -m pip wheel --no-deps -w dist/ .
#           displayName: 'Python build'
  
#         - script: |
#             ls -lah dist
#             twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.whl dist/*.tar.gz
#           env:
#             TWINE_USERNAME: $(pypi_user_global)
#             TWINE_PASSWORD: $(pypi_token_global)
#           displayName: Upload to PyPI