trigger:
  batch: true
  branches:
    include:
    - '*'

variables:
  - group: gswa-pypi
  - group: gswa-jfrog
  - group: github_tokens
  # used to name repo
  - name: project_name
    value: "atratus"
  # for releases
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  # for integration testing
  - name: isRC
    value: $[contains(variables['Build.SourceBranch'], 'releases/')]
  # for modifying/reviewing pipeline
  - name: isCICD 
    value: $[contains(variables['Build.SourceBranch'], 'cicd')]
  # these will need to be updated for each repo
  - name: isTAGGED
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]


pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  displayName: 'Unit Tests'
  condition: always()
  jobs:
    - job: TestCoverage
      displayName: 'Test coverage'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: '.[tests] pytest-azurepipelines'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m pytest --cov-report xml:tests/cov.xml --cov tests/
          displayName: 'Test .[tests]'
        
        - task: PublishCodeCoverageResults@2
          inputs:
            summaryFileLocation: '**/tests/cov.xml'
            pathToSources: '$(System.DefaultWorkingDirectory)/src/'
            failIfCoverageEmpty: true

- stage: Xray
  displayName: 'Xray Scan'
  trigger: manual
  isSkippable: false
  jobs:
    - job: BuildDependencies
      displayName: 'Install, build, and scan'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m build .
          displayName: 'Python build'
        
        - script: |
              curl -fL https://install-cli.jfrog.io | sh
              jf config add jfrog-bot \
              --url="$(JFROG_URL)" \
              --access-token="$JFROG_ACCESS_TOKEN" \
              --interactive=false
          env:
            JFROG_URL: $(jfrog_url)
            JFROG_ACCESS_TOKEN: $(jfrog-bot-token)
          displayName: Install and configure JFrog CLI

        - script: |
            jf scan dist/ --format='json' > xray.json
            jf scan dist/ --format='sarif' > xray.sarif
          displayName: 'Xray Scan'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: xray.sarif
            artifactName: CodeAnalysisLogs
          env:
            BUILD_NAME: $(Build.DefinitionName)
            BUILD_NUMBER: $(Build.BuildNumber)
          displayName: 'Publish SARIF artifact'

        - script: |
            python - <<'EOF'
            import json
            import sys
            sarif_file = "xray.json"
            with open(sarif_file, "r", encoding="utf-8") as f:
                data = json.load(f)

            scanned_components = [
                item["component_id"]
                for item in data
                if "components"
                if "component_id" in item.keys()
            ]
            
         
            if "vulnerabilities" not in data[-1].keys():
              print("No vulnerabilities detected")
              sys.exit(0)
            elif  "vulnerabilities" in data[-1].keys(): 
              num_vulnerabilities = len(data[-1]["vulnerabilities"])
              if num_vulnerabilities > 0:
                  print(f"{num_vulnerabilities} High or Critical vulnerabilities detected")
                  sys.exit(1)


          displayName: 'Parse Vulnerabilities in xray Report'

- stage: DevBuild
  displayName: 'JFrog Build and Publish'
  condition: and( succeeded('Test'), succeeded('Xray'), or(eq(variables.isMain, true), eq(variables.isRC, true), eq(variables.isCICD, true)) )
  dependsOn: 
    - Test
    - Xray
  jobs:
    - job: BuildDependencies
      displayName: 'Install and build'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'
        
        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m pip install build
            python -m build .
          displayName: 'Python build'

        - script: |
            ls -lah dist/ 
            twine upload --repository-url $(artifactory_pypi_url) dist/*
          env:
            TWINE_USERNAME: $(jfrog_bot_username)
            TWINE_PASSWORD: $(jfrog-bot-token)
          displayName: Upload to JFrog Artifactory

# builds and releases to pypi-test
- stage: Test_Release
  displayName: 'Publish to Test - PyPi'
  dependsOn: 
    - Test
    - Xray
    - DevBuild
  condition: and( 
    succeeded('Test'), 
    succeeded('Xray'), 
    succeeded('DevBuild'),
    or(eq(variables.isMain, true), eq(variables.isCICD, true)),
    eq(variables.isTAGGED, true)
    )
  jobs:
    - job: BuildDependencies
      displayName: 'Install, build, and scan'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m build .
          displayName: 'Python build'
  
        - script: |
            ls -lah dist
            twine upload --repository testpypi dist/* --verbose
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: $(test_pypi_token_global)
          displayName: 'Upload to TestPyPI'


- stage: Release
  displayName: 'Publish to PyPi'
  dependsOn: 
    - Test
    - Xray
    - DevBuild
    - Test_Release
  condition: and( succeeded('Test'), succeeded('Xray'), succeeded('Build'), eq(variables.isMain, true))
  jobs:
    - job: BuildDependencies
      displayName: 'Install, build, and scan'
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.12'
            addToPath: true
            architecture: 'x64'

        - task: JFrogPip@1
          inputs:
            artifactoryConnection: 'service-ado-jfrog-geodigital'
            command: 'install'
            arguments: 'twine build .[tests,dev]'
            targetResolveRepo: 'gswa-pypi-virtual'

        - script: |
            python -m build .
          displayName: 'Python build'
  
        - script: |
            ls -lah dist
            twine upload dist/* --verbose
          env:
            TWINE_USERNAME: __token__
            TWINE_PASSWORD: $(pypi_token_global)
          displayName: 'Upload to TestPyPI'

# see if requires tag
- stage: Github
  displayName: 'Publish to GitHub'
  dependsOn: 
    - Test
    - Xray
    - DevBuild
    - Test_Release
  condition: and( 
    succeeded('Test'), 
    succeeded('Xray'), 
    succeeded('Build'),  
    or(eq(variables.isMain, true), eq(variables.isCICD, true)),
    eq(variables.isTAGGED, true)
    )
  jobs:
    - job: Mirror
      displayName: 'Mirror to GitHub'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - checkout: self
        fetchDepth: 0   # REQUIRED for full history & tags

      - script: |
          echo "Checking if GitHub repo exists..."

          curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token $(atratus_ado_bot)" \
            https://api.github.com/repos/$(github_org)/$(github_repo_name) > status.txt

          STATUS=$(cat status.txt)

          if [ "$STATUS" = "404" ]; then
            echo "Repo does not exist. Creating..."
            curl -X POST \
              -H "Authorization: token $(github_pat)" \
              https://api.github.com/orgs/$(github_org)/repos \
              -d '{
                "name": "$(github_repo_name)",
                "private": false
              }'
          else
            echo "Repo already exists."
          fi
        displayName: 'Ensure GitHub Repo Exists'

      - script: |
          echo "Adding GitHub remote..."

          git remote remove github 2>/dev/null || true

          git remote add github https://$(github_pat)@github.com/$(github_org)/$(github_repo_name).git

          echo "Pushing full mirror..."
          git push --mirror github
        displayName: 'Mirror Repository to GitHub'